CREATE UNIQUE INDEX IF NOT EXISTS "slug_city_id_idx" ON "cities" USING btree ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "slug_district_id_idx" ON "districts" USING btree ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "slug_place_id_idx" ON "places" USING btree ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "slug_ward_id_idx" ON "wards" USING btree ("slug");
CREATE INDEX IF NOT EXISTS "spa_external_reviews_spa_id_idx" ON "spa_external_reviews" USING btree ("spa_id");
CREATE INDEX IF NOT EXISTS "spa_galleries_spa_id_idx" ON "spa_galleries" USING btree ("spa_id");
CREATE INDEX IF NOT EXISTS "spa_locations_spa_id_idx" ON "spa_locations" USING btree ("spa_id");
CREATE INDEX IF NOT EXISTS "spa_locations_city_id_idx" ON "spa_locations" USING btree ("city_id");
CREATE INDEX IF NOT EXISTS "spa_locations_district_id_idx" ON "spa_locations" USING btree ("district_id");
CREATE INDEX IF NOT EXISTS "spa_locations_ward_id_idx" ON "spa_locations" USING btree ("ward_id");
CREATE INDEX IF NOT EXISTS "spa_locations_place_id_idx" ON "spa_locations" USING btree ("place_id");
CREATE UNIQUE INDEX IF NOT EXISTS "slug_idx" ON "spas" USING btree ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "slug_vi_idx" ON "spas" USING btree ("slug_vi");
CREATE UNIQUE INDEX IF NOT EXISTS "slug_en_idx" ON "spas" USING btree ("slug_en");
CREATE UNIQUE INDEX IF NOT EXISTS "slug_ko_idx" ON "spas" USING btree ("slug_ko");
CREATE INDEX IF NOT EXISTS "deal_variant_prices_variant_id_idx" ON "deal_variant_prices" USING btree ("variant_id");
CREATE INDEX IF NOT EXISTS "deal_variants_deal_id_idx" ON "deal_variants" USING btree ("deal_id");
CREATE INDEX IF NOT EXISTS "deals_spa_id_idx" ON "deals" USING btree ("spa_id");
CREATE INDEX IF NOT EXISTS "deals_category_id_idx" ON "deals" USING btree ("category_id");
CREATE INDEX IF NOT EXISTS "deals_city_id_idx" ON "deals" USING btree ("city_id");
CREATE INDEX IF NOT EXISTS "deals_district_id_idx" ON "deals" USING btree ("district_id");
CREATE INDEX IF NOT EXISTS "deals_status_idx" ON "deals" USING btree ("status");
CREATE INDEX IF NOT EXISTS "deals_ward_id_idx" ON "deals" USING btree ("ward_id");
CREATE INDEX IF NOT EXISTS "deals_place_id_idx" ON "deals" USING btree ("place_id");
CREATE UNIQUE INDEX IF NOT EXISTS "slug_global_idx" ON "services" USING btree ("slug_global");
CREATE UNIQUE INDEX IF NOT EXISTS "services_slug_vi_idx" ON "services" USING btree ("slug_vi");
CREATE UNIQUE INDEX IF NOT EXISTS "services_slug_en_idx" ON "services" USING btree ("slug_en");
CREATE UNIQUE INDEX IF NOT EXISTS "services_slug_ko_idx" ON "services" USING btree ("slug_ko");
CREATE INDEX IF NOT EXISTS "url_locale_idx" ON "seo_nodes" USING btree ("url","locale","publish_status");
CREATE INDEX IF NOT EXISTS "slot_key_idx" ON "homepage_slots" USING btree ("slot_key","locale");
CREATE INDEX IF NOT EXISTS "entity_type_slug_type_idx" ON "tracking_events" USING btree ("entity_type","entity_slug","event_type");