'use client';
import { useEffect } from 'react';
import { usePathname } from 'next/navigation';

// This flag indicates if the app has completed its initial render/hydration.
// It is false on a fresh page load (e.g. opening a link in a new tab),
// and becomes true immediately after the root layout effects run.
export let isAppHydrated = false;

export function HistoryPatchProvider() {
  const pathname = usePathname();

  useEffect(() => {
    isAppHydrated = true;
  }, []);

  // Cleanup accumulated hreflang tags generated by Next.js on client navigation
  useEffect(() => {
    const links = document.querySelectorAll('link[rel="alternate"][hreflang]');
    
    // Create a map to keep only the LAST inserted tag for each hreflang
    // Next.js usually appends new ones to the end
    const latestByLang = new Map<string, Element>();
    
    links.forEach(link => {
      const hreflang = link.getAttribute('hreflang');
      if (hreflang) {
        latestByLang.set(hreflang, link);
      }
    });

    // Remove all link tags that are not the latest ones
    links.forEach(link => {
      const hreflang = link.getAttribute('hreflang');
      if (hreflang && latestByLang.get(hreflang) !== link) {
        link.remove();
      }
    });
  }, [pathname]);

  return null;
}
